### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by DvLAx3l** [Magisk-Modules-Repo/pixel-complementary-live-wallpapers#3]
It gives error during installation when trying to unzip the file.
I'm on Pixel 3XL June update with magisk 19.3, here is the install log.
[magisk_install_log_2019-06-157T14:22:34Z.log](https://github.com/Magisk-Modules-Repo/pixel-complementary-live-wallpapers/files/3261500/magisk_install_log_2019-06-157T14.22.34Z.log)

**Comment by Supoyuan** [comment]
![issue](https://user-images.githubusercontent.com/51680352/59225936-8cb5e700-8c04-11e9-83f4-ca52f724a49c.png)

delete old files in zip.
only need lastest dir "2019-06-05".
and can install success.

**Comment by DvLAx3l** [comment]
Like this it work, but some wallpapers crash.
I've tried also the v2 out now on the repo, it install, but some walls still crash.

**Comment by igor-dyatlov** [comment]
@DvLAx3l In the new version of the module, the wallpaper is downloaded from the cloud. What crashs did you see?
