### ISSUE TITLE
Not available

### ISSUE THREAD

**Issue by az1250424491** [Magisk-Modules-Repo/pixel-complementary-live-wallpapers#5]
Google pixels are not available. I am using Android pie.

![Screenshot_20190704-190328](https://user-images.githubusercontent.com/33147999/60663093-d060e100-9e90-11e9-9ac0-895b274e0041.png)
![Screenshot_20190704-190345](https://user-images.githubusercontent.com/33147999/60663095-d0f97780-9e90-11e9-9294-ce88357ed311.png)
![Screenshot_20190704-190716](https://user-images.githubusercontent.com/33147999/60663096-d0f97780-9e90-11e9-90f8-dd569419ba91.png)

e90-11e9-9ce3-a070887b7c24.png)

**Comment by jgben12** [comment]
The same error as my Pixel XL(Android Q beta 5).
I install APK from APK mirror directly.
If your phone is running Pie, maybe you could download APK and install, as when I used Pie, some wallpapers work well at least.

**Comment by vonDubenshire** [comment]
> The same error as my Pixel XL(Android Q beta 5).
> I install APK from APK mirror directly.
> If your phone is running Pie, maybe you could download APK and install, as when I used Pie, some wallpapers work well at least.

Are you using the APK Mirror file from Google itself?

**Comment by igor-dyatlov** [comment]
@az1250424491 @jgben12 The error was in the absence of the required libraries. Fixed in the new version.
