### ISSUE TITLE
Fail to apply the wallpaper of XL / 2XL on 3XL

### ISSUE THREAD

**Issue by Chekky** [Magisk-Modules-Repo/pixel-complementary-live-wallpapers#6]
Fail to apply the wallpaper of XL / 2XL on 3XL(2019 July update), it said 2017 pixel wallpaper stoped.
![Screenshot_20190711-085106](https://user-images.githubusercontent.com/18340447/61014268-32ea3d80-a3b9-11e9-8292-6329e49c561e.png)

**Comment by roll3r** [comment]
Same. Pixel 3XL stock July update.

**Comment by vonDubenshire** [comment]
I am having the same issue.  I could not get the Pixel 2 or Pixel 1 wallpapers to load, it crashed every time on the June patch and now also on the July.

I just reformatted my phone and now I cannot access the module's 530mb download whatsoever.  It fails and says I need an internet connection every time -- I have done everything to account for this with no luck.

Pixel 3 here.  Latest version of module installs and then checks internet and fails. 

Any fixes?

**Comment by igor-dyatlov** [comment]
@vonDubenshire The error was in the absence of the required libraries. Fixed in the new version.
