### ISSUE TITLE
"No Internet Connection" on Pixel 3XL on August 2019 

### ISSUE THREAD

**Issue by Eudeferrer** [Magisk-Modules-Repo/pixel-complementary-live-wallpapers#7]
No matter what I do, it always says that I have "no internet connection". I am on latest Aug patch. I cannot access the module's 530mb download. This happens even though it downloads the module itself from the Magisk Repo. How can I fix this?

**Comment by vonDubenshire** [comment]
I have been having the same issue since beginning of July on Pixel 3 regular.

**Comment by vonDubenshire** [comment]
I figured out an issue. If this is hosted on source forge it is not allowing me to download there for some reason. They don't allow this device to download from their servers

**Comment by Chekky** [comment]
me too

**Comment by igor-dyatlov** [comment]
@Eudeferrer @vonDubenshire @Chekky Fixed in new version. 
[magisk_install_log_2019-09-03T19:45:40Z.log](https://github.com/Magisk-Modules-Repo/pixel-complementary-live-wallpapers/files/3570548/magisk_install_log_2019-09-03T19.45.40Z.log)

**Comment by Eudeferrer** [comment]
Just tried installing through magisk and got the same error.

**Comment by Chekky** [comment]
me too, +1.


On 9/4/2019 02:14，Eudeferrer<notifications@github.com> wrote：
Just tried installing through magisk and got the same error.

**Comment by igor-dyatlov** [comment]
@Eudeferrer Please send a log

**Comment by Chekky** [comment]
- Copying zip to temp directory
- Installing Pixel_Complementary_Live_Wallpapers-v2.1.1.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/install.zip
  inflating: post-fs-data.sh
  inflating: service.sh
  inflating: system.prop
  inflating: install.sh
  inflating: module.prop
****************************************************
     Magisk Pixel Complementary Live Wallpapers     
                by @igor-dyatlov                    
****************************************************
******************************
Powered by Magisk (@topjohnwu)
******************************
Installing  Module!
Performing compatibility check...
Device: crosshatch
Android version: 9
Security patch version: 2019-08-01
Your device is compatible. Continue with installation.
Downloading module files for 'crosshatch' and Android Version '9'
Check Internet connection...
wget: download timed out
Internet connection is not available. Check the connection and try again.
! Installation failed


On 9/4/2019 12:57，Igor Dyatlov<notifications@github.com> wrote：

@Eudeferrer Please send a log

**Comment by luciodaou** [comment]
Somehow it worked to me after updating "GNU Utils" module.
Android 10, Pixel 2. Magisk on Ianmacd repo.

**Comment by Eudeferrer** [comment]
It doesn't seem to work on Pixel 3XL.

**Comment by step-2** [comment]
same issue here on Android 10 pixel 3a

**Comment by waaagh313ph4n7** [comment]
I have the same problem and took a look at the install script. It seems it uses this command to check for an internet connection:

wget -q --tries=10 --timeout=20 --spider https://google.com

I tried it in a terminal and get an error about failed TLS verification. Turns out the version of wget provided by osm0sis busybox does not support https. Without busybox it fails as well, since there is no wget at all.

I'm on a Pixel 2XL with Android 10.

**Comment by fox8091** [comment]
Pixel 2, same issue. Wget is failing.

**Comment by jamesli1258** [comment]
still doesnt work

**Comment by Eudeferrer** [comment]
Yes. I'm still having same problem as well.

**Comment by vonDubenshire** [comment]
Nothing still. Really?

**Comment by JhihYuWong** [comment]
same issue here on Android 10 Pixel 2

**Comment by igor-dyatlov** [comment]
@luciodaou Internet access check command did not work correctly. This module adds these tools to the system.
@Eudeferrer @fox8091 @waaagh313ph4n7 @jamesli1258 @vonDubenshire @JhihYuWong Fixed in the new version.
