### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by wewillchenoob** [Magisk-Modules-Repo/pixel-complementary-live-wallpapers#8]
Device: blueline
Android version: 10
Log: 
- Copying zip to temp directory
- Installing Pixel_Complementary_Live_Wallpapers-v2.1.1(8).zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh
  inflating: service.sh
  inflating: system.prop
  inflating: install.sh
  inflating: module.prop
****************************************************
     Magisk Pixel Complementary Live Wallpapers     
                by @igor-dyatlov                    
****************************************************
******************************
Powered by Magisk (@topjohnwu)
******************************
Installing  Module!
Performing compatibility check...
Device: blueline
Android version: 10
Security patch version: 2019-09-05
Your device is compatible. Continue with installation.
update-binary: .: line 230: can't open '/dev/tmp/device/10/.sh': No such file or directory
! Installation failed

**Comment by luciodaou** [comment]
Same thing here.

**Comment by danteissaias** [comment]
+1

**Comment by Chekky** [comment]
+1

**Comment by LeehsinZhang** [comment]
wget bad address ’google.com’

**Comment by vonDubenshire** [comment]
This has been going on for months.

Does no one care?

**Comment by Chekky** [comment]
I find that ping and wget all return with error code 1, maybe can't find ping and wget command?

**Comment by igor-dyatlov** [comment]
@danteissaias Installer replaced by curl library
