### ISSUE TITLE
Pixel 2XL installation fail

### ISSUE THREAD

**Issue by m0n5t4H** [Magisk-Modules-Repo/pixel-complementary-live-wallpapers#9]
I've tried installing this module

```
Installing Module!
Performaing compatibility check...
Device: taimen
Android Version: 10
Security Patch Version: 2019-10-06
Your device is compatible. Continue with installation.
! Installation failed
```

once it fails it actually shows up under modules:

> pixel-complementary-live-wallpapers
> _(No info provided)
> (No info provided)_
> (No info provided)

**Comment by gregthwuen** [comment]
Exactly the same on Pixel 3a XL (Bonito)

**Comment by m0n5t4H** [comment]
Update doesn't fix the issue now my installation fails due to no internet, 


- Copying zip to temp directory
- Installing Pixel_Complementary_Live_Wallpapers-v3.0.2(10).zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh
  inflating: service.sh
  inflating: system.prop
  inflating: install.sh
  inflating: module.prop
****************************************************
     Magisk Pixel Complementary Live Wallpapers     
                by @igor-dyatlov                    
****************************************************
******************************
Powered by Magisk (@topjohnwu)
******************************
Installing  Module!
Performing compatibility check...
Device: taimen
Android version: 10
Security patch version: 2019-10-06
Your device is compatible. Continue with installation.
Downloading module files for 'taimen' and Android Version '10'
Check Internet connection...
wget: bad address 'google.com'
Internet connection is not available. Check the connection and try again.
! Installation failed

**Comment by DvLAx3l** [comment]
Also on Pixel 3 XL with v3.0.3 says no internet connection during the installation process
